### ISSUE TITLE
Foodvisor puts all products in Ireland ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/contributor-quality-issues#7]
### What
- https://world.openfoodfacts.org/product/0665593005667/quiche-lorraine-carrefour#
- Foodvisor puts all products in Ireland ?

**Comment by CharlesNepote** [comment]
No, [less than 30%](https://mirabelle.openfoodfacts.org/products?sql=select+%2F*code%2C+url%2C+*%2Fcreator%0D%0A--%2C+created_datetime%2C+last_modified_datetime%0D%0A%2C+last_modified_by%0D%0A--%2C+product_name%0D%0A--%2C+abbreviated_product_name%2C+generic_name%2C+quantity%2C+packaging%2C+packaging_tags%2C+packaging_en%2C+packaging_text%0D%0A--%2C+brands%0D%0A--%2C+brands_tags%2C+categories%2C+categories_tags%2C+categories_en%2C+origins%2C+origins_tags%2C+origins_en%2C+manufacturing_places%2C+manufacturing_places_tags%2C+labels%2C+labels_tags%2C+labels_en%2C+emb_codes%2C+emb_codes_tags%2C+first_packaging_code_geo%0D%0A--%2C+cities%2C+cities_tags%2C+purchase_places%2C+stores%0D%0A%2C+countries%0D%0A%2C+count%28countries%29%0D%0A%2C+round%28%0D%0A+++++++CAST%28count%28countries%29+as+REAL%29%0D%0A+++++++%2F%28select+count%28code%29+from+%5Ball%5D+where+creator+%3D%3D+%22foodvisor%22+and+last_modified_by+%3D%3D+%22foodvisor%22%29%0D%0A+++++++*100%2C2%0D%0A+++++++%29+as+%22%25_tot%22%0D%0Afrom+%5Ball%5D%0D%0Awhere+creator+%3D%3D+%22foodvisor%22%0D%0Aand+last_modified_by+%3D%3D+%22foodvisor%22%0D%0A--and+created_datetime+%3E+%222023-06%22%0D%0Agroup+by+countries%0D%0Aorder+by+count%28countries%29+desc%0D%0A--order+by+random%28%29%0D%0Alimit+500).

[No more since 2023-11-22](https://mirabelle.openfoodfacts.org/products?sql=select+code%2C+url%2C+creator%2C+created_datetime%2C+last_modified_datetime%2C+last_modified_by%0D%0A--%2C+product_name%0D%0A--%2C+abbreviated_product_name%2C+generic_name%2C+quantity%2C+packaging%2C+packaging_tags%2C+packaging_en%2C+packaging_text%0D%0A%2C+brands%0D%0A--%2C+brands_tags%2C+categories%2C+categories_tags%2C+categories_en%2C+origins%2C+origins_tags%2C+origins_en%2C+manufacturing_places%2C+manufacturing_places_tags%2C+labels%2C+labels_tags%2C+labels_en%2C+emb_codes%2C+emb_codes_tags%2C+first_packaging_code_geo%0D%0A--%2C+cities%2C+cities_tags%2C+purchase_places%2C+stores%0D%0A%2C+countries%0D%0Afrom+%5Ball%5D%0D%0Awhere+creator+%3D%3D+%22foodvisor%22%0D%0Aand+last_modified_by+%3D%3D+%22foodvisor%22%0D%0Aorder+by+created_datetime+desc%0D%0Alimit+2500).
